"""Add password reset fields to users table

Revision ID: 8d50c9132e8f
Revises: 001_init_auth
Create Date: 2025-10-20 14:42:38.822051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d50c9132e8f'
down_revision: Union[str, None] = '001_init_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """업그레이드 작업"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """다운그레이드 작업"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
